
#include "../include/testDeviceDataGen_DBL.h"
#include <nds3/nds.h>
#include <mutex>
#include <unistd.h>
#include <functional>

static std::map<std::string, testDeviceDataGenDBL*> m_devicesMap;
static std::mutex m_lockDevicesMap;

testDeviceDataGenDBL::testDeviceDataGenDBL(nds::Factory &factory, const std::string &deviceName, const nds::namedParameters_t &parameters):
	m_name(deviceName),	timestamp_device{0,0},readtimeStamp{0,0}
{
	//TODO:Study this.
	{
		std::lock_guard<std::mutex> lock(m_lockDevicesMap);
		if(m_devicesMap.find(deviceName) != m_devicesMap.end())
		{
			throw std::logic_error("Device with the same name already allocated. This should not happen");
		}
		m_devicesMap[deviceName] = this;
	}

	/**
	 * Here we declare the root node.
	 * It is a good practice to name it with the device name.
	 *
	 * Also, for simplicity we declare it as a "Port": this means that
	 * the root node will be responsible for the communication with
	 * the underlying control system.
	 *
	 * It is possible to have the root node as a simple Node and promote one or
	 * more of its children to "Port": each port will interface with a different
	 * control system thread.
	 */
	nds::Port rootNode(deviceName);

	// Add state machine
	m_testDeviceDataGenDBL_stateMachine = rootNode.addChild(nds::StateMachine(true,
			std::bind(&testDeviceDataGenDBL::switchOn_testDeviceDataGenDBL, this),
			std::bind(&testDeviceDataGenDBL::switchOff_testDeviceDataGenDBL, this),
			std::bind(&testDeviceDataGenDBL::start_testDeviceDataGenDBL, this),
			std::bind(&testDeviceDataGenDBL::stop_testDeviceDataGenDBL, this),
			std::bind(&testDeviceDataGenDBL::recover_testDeviceDataGenDBL, this),
			std::bind(&testDeviceDataGenDBL::allow__testDeviceDataGenDBL_Change,this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3)));



	/**
	 * Add a DataGeneration node: it acquires data generated by the DataGeneration node and supplies an input PV on which we can push the
	 * acquired data, it also adds a state machine that allows to start and stop the acquisition.
	 */
	m_DataGeneration = rootNode.addChild(nds::DataGeneration<double>(
			"DataGenerationNode",
			1,
			std::bind(&testDeviceDataGenDBL::switchOn_DataGeneration, this),
			std::bind(&testDeviceDataGenDBL::switchOff_DataGeneration, this),
			std::bind(&testDeviceDataGenDBL::start_DataGeneration, this),
			std::bind(&testDeviceDataGenDBL::stop_DataGeneration, this),
			std::bind(&testDeviceDataGenDBL::recover_DataGeneration, this),
			std::bind(&testDeviceDataGenDBL::allow_DataGeneration_Change, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Frequency_Writer,this, std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_RefFrequency_Writer,this, std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Amp_Writer,this, std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Phase_Writer,this, std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_UpdateRate_Writer,this,  std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_DutyCycle_Writer,this,  std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Gain_Writer,this, std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Offset_Writer,this, std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Bandwidth_Writer,this, std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Resolution_Writer,this, std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Impedance_Writer,this,  std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Coupling_Writer,this,   std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_SignalRef_Writer,this,  std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_SignalType_Writer,this,  std::placeholders::_1, std::placeholders::_2),
			std::bind(&testDeviceDataGenDBL::PV_DataGeneration_Ground_Writer,this, std::placeholders::_1, std::placeholders::_2)
	));

	// We have declared all the nodes and PVs in our device: now we register them
	//  with the control system that called this constructor.
	////////////////////////////////////////////////////////////////////////////////
	rootNode.initialize(this, factory);
}



testDeviceDataGenDBL::~testDeviceDataGenDBL()
{
    std::lock_guard<std::mutex> lock(m_lockDevicesMap);
    m_devicesMap.erase(m_name);

}

testDeviceDataGenDBL* testDeviceDataGenDBL::getInstance(const std::string& deviceName)
{
    std::lock_guard<std::mutex> lock(m_lockDevicesMap);

    std::map<std::string, testDeviceDataGenDBL*>::const_iterator findDevice = m_devicesMap.find(deviceName);
    if(findDevice == m_devicesMap.end())
    {
        return 0;
    }
    return findDevice->second;
}

/*
 * Allocation function
 *********************/
void* testDeviceDataGenDBL::allocateDevice(nds::Factory& factory, const std::string& deviceName, const nds::namedParameters_t& parameters)
{
    return new testDeviceDataGenDBL(factory, deviceName, parameters);
}

/*
 * Deallocation function
 ***********************/
void testDeviceDataGenDBL::deallocateDevice(void* deviceName)
{
    delete (testDeviceDataGenDBL*)deviceName;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////
//  TEST DEVICE STATE MACHINE
///////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Methods to control testDeviceDataGenDBL state machine
 */
void testDeviceDataGenDBL::switchOn_testDeviceDataGenDBL(){

}
void testDeviceDataGenDBL::switchOff_testDeviceDataGenDBL(){

}
void testDeviceDataGenDBL::start_testDeviceDataGenDBL(){

}
void testDeviceDataGenDBL::stop_testDeviceDataGenDBL(){

}
void testDeviceDataGenDBL::recover_testDeviceDataGenDBL(){

}

bool testDeviceDataGenDBL::allow__testDeviceDataGenDBL_Change(const nds::state_t, const nds::state_t, const nds::state_t){
	return true;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////
// DATA GENERATION NODE*/
////////////////////////////////////////////////////////////////////////////////////////////////////////

/*
* DataGeneration State Machine
*/

void testDeviceDataGenDBL::switchOn_DataGeneration(){

}

void testDeviceDataGenDBL::switchOff_DataGeneration(){

}

void testDeviceDataGenDBL::start_DataGeneration(){
	m_bStop_DataGeneration = false; //< We will set to true to stop the acquisition thread
	/**
	 *   Start the acquisition thread.
	 *   We don't need to check if the thread was already started because the state
	 *   machine guarantees that the start handler is called only while the state
	 *   is ON.
	 */
	m_DataGeneration_Thread = std::thread(std::bind(&testDeviceDataGenDBL::DataGeneration_thread_body, this));
}

void testDeviceDataGenDBL::stop_DataGeneration(){
	m_bStop_DataGeneration = true;
	m_DataGeneration_Thread.join();
}

void testDeviceDataGenDBL::recover_DataGeneration(){
    throw nds::StateMachineRollBack("Cannot recover"); //TODO: Study this
}

bool testDeviceDataGenDBL::allow_DataGeneration_Change(const nds::state_t, const nds::state_t, const nds::state_t){
	return true;
}

/*
* DataGeneration setters
*/
void testDeviceDataGenDBL::PV_DataGeneration_Frequency_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the frequency to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real frequency programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setFrequency(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_RefFrequency_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the RefFrequency to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real RefFrequency programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setRefFrequency(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Amp_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//value has the amplitude to be programmed on the hardware
	//call to function programming the hardware. This function should return the real amplitude programmed. This value has to be set to the readback attribute.
	//in the meantime without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setAmplitude(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Phase_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the Phase to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real Phase programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setPhase(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_UpdateRate_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the UpdateRate to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real UpdateRate programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setUpdateRate(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_DutyCycle_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the DutyCycle to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real DutyCycle programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setDutyCycle(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Gain_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the Gain to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real Gain programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setGain(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Offset_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the Offset to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real Offset programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setOffset(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Bandwidth_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the Bandwidth to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real Bandwidth programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setBandwidth(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Resolution_Writer(const timespec& timestamp, const double& value){
	double HW_value;
	//Value has the Resolution to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real Resolution programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setResolution(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Impedance_Writer(const timespec& timestamp, const std::int32_t& value){
	std::int32_t HW_value;
	//Value has the Impedance to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real Impedance programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setImpedance(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Coupling_Writer(const timespec& timestamp, const std::int32_t& value){
	std::int32_t HW_value;
	//Value has the Coupling to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real Coupling programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setCoupling(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_SignalRef_Writer(const timespec& timestamp, const std::int32_t& value){
	std::int32_t HW_value;
	//Value has the SignalRef to be programmed on the hardware.
	//Call to function programming the hardware. This function should return the real SignalRef programmed. This value has to be set to the readback attribute.
	//In the meantime, without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setSignalRef(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_SignalType_Writer(const timespec& timestamp, const std::int32_t& value){
	std::int32_t HW_value;
	//value has the SignalType to be programmed on the hardware
	//call to function programming the hardware. This function should return the real SignalType programmed. This value has to be set to the readback attribute.
	//in the meantime without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setSignalType(timestamp,HW_value);
}
void testDeviceDataGenDBL::PV_DataGeneration_Ground_Writer(const timespec& timestamp, const std::int32_t& value){
	std::int32_t HW_value;
	//value has the Ground to be programmed on the hardware
	//call to function programming the hardware. This function should return the real Ground programmed. This value has to be set to the readback attribute.
	//in the meantime without real hardware value and  HW_value are equal.
	HW_value=value;
	m_DataGeneration.setGround(timestamp,HW_value);
}

/*
* Body of function to generate data. In this example we are going to generate a sine wave.
*/
void testDeviceDataGenDBL::DataGeneration_thread_body(){

	// Let's allocate a vector that will contain the data that we will push to the control system or to the data acquisition node
	double outputData(0);

	//Counter for number of pushed data blocks
	std::int32_t NumberOfPushedDataBlocks(0);

	// A counter for the angle in the sin() operation
	std::int64_t angle(0);

	size_t last_sample(0);

	// Get RefFrequency
	double RefFrequency = m_DataGeneration.getRefFrequency();
	// Get DutyCycle
	double DutyCycle = m_DataGeneration.getDutyCycle();
	// Get Gain
	double Gain = m_DataGeneration.getGain();
	// Get Bandwidth
	double Bandwidth = m_DataGeneration.getBandwidth();
	// Get Resolution
	double Resolution = m_DataGeneration.getResolution();
	// Get Coupling
	double Coupling = m_DataGeneration.getCoupling();
	// Get SignalRef
	double SignalRef = m_DataGeneration.getSignalRef();
	// Get Ground
	double Ground = m_DataGeneration.getGround();

	std::cout<<"Signal generator configured with:"<<std::endl;
	std::cout<<"\tRefFrequency = "<<RefFrequency<<std::endl;
	std::cout<<"\tDutyCycle = "<<DutyCycle<<std::endl;
	std::cout<<"\tGain = "<<Gain<<std::endl;
	std::cout<<"\tBandwidth = "<<Bandwidth<<std::endl;
	std::cout<<"\tResolution = "<<Resolution<<std::endl;
	std::cout<<"\tCoupling = "<<Coupling<<std::endl;
	std::cout<<"\tSignalRef = "<<SignalRef<<std::endl;
	std::cout<<"\tGround = "<<Ground<<std::endl;

	// Run until the state machine stops us
	while(!m_bStop_DataGeneration){

		// Get signalType
		size_t signalType = m_DataGeneration.getSignalType();
		// Get amplitude
		double amplitude = m_DataGeneration.getAmplitude();
		// Get frequency
		double frequency = m_DataGeneration.getFrequency();
		// Get updateRate
		double updateRate = m_DataGeneration.getUpdateRate();
		// Get offset
		double offset = m_DataGeneration.getOffset();
		// Get phase
		double phase = m_DataGeneration.getPhase();
		// Get phase
		double impedance = m_DataGeneration.getImpedance();

		switch(signalType){

			case 0:
					outputData = amplitude;
				break;
			case 1:
					outputData = amplitude;
				break;
			case 2:
					outputData = amplitude;

				break;
			case 3:
					outputData = (double)amplitude * sin((2*M_PI*(last_sample)*frequency)/updateRate + phase) + offset;

				break;
			case 4:
					outputData = ((angle & 0xff) < 128) ? amplitude : - amplitude;

				break;
			case 5:
					outputData = amplitude;

				break;
			case 6:
					outputData = amplitude;

				break;
			case 7:
					outputData = amplitude;

				break;
			default:
					outputData = amplitude;

				break;
		}

		//Save last sample generated.
		last_sample++;

	// Push the vector to the control system
	m_DataGeneration.push(m_DataGeneration.getTimestamp(), outputData);
	++NumberOfPushedDataBlocks;
	//TODO: Send values to data acquisition node.

	// Rest for a while
	::usleep(40000);
	}
	m_DataGeneration.setNumberOfPushedDataBlocks(m_DataGeneration.getTimestamp(),NumberOfPushedDataBlocks);
}


