#ifndef DEVICEVECTORUI8_H_
#define DEVICEVECTORUI8_H_

#include <memory>

#include <functional>
#include <math.h>
#include <unistd.h>
#include <iostream>
#include <thread>

#include <nds3/nds.h>

/**
 * @brief Class that declares and implement a fictional device for testing purposes of nds-core V3.
 *
 *
 * The class does not need to be derived from any special class, but its constructor must
 *  accept few mandatory parameters and should register the root node via Node::initialize().
 */
class DeviceVectorUI8
{
public:
	/**
	 * @brief Constructor.
	 *
	 * @param factory    the control system factory that requested the creation of the device
	 * @param device     the name given to the device
	 * @param parameters optional parameters passed to the device
	 */
	DeviceVectorUI8(nds::Factory& factory, const std::string& deviceName, const nds::namedParameters_t& );
	~DeviceVectorUI8();

	/*
	 * Allocation/deallocation
	 *
	 *******************************************************/
	static void* allocateDevice(nds::Factory& factory, const std::string& deviceName, const nds::namedParameters_t& parameters);
	static void deallocateDevice(void* deviceName);

	/*
	 * For test purposes we make it possible to retrieve running instances of
	 *  the device
	 */
	static DeviceVectorUI8* getInstance(const std::string& deviceName);


private:

	/*
	 * @brief name of the device
	 */
	std::string m_name;

	timespec timestamp_device, readtimeStamp;

	///////////////////////////////////////////////////////////////////////////////////////////////////////
	//  TEST DEVICE STATE MACHINE
	///////////////////////////////////////////////////////////////////////////////////////////////////////

	/**
	 * @brief DeviceVectorUI8 state machine
	 */
	nds::StateMachine m_DeviceVectorUI8_stateMachine;

	/**
	 * Methods to control DeviceVectorUI8 state machine
	 */
	void switchOn_DeviceVectorUI8();  ///< Called to switch on the DeviceVectorUI8 (rootnode).
	void switchOff_DeviceVectorUI8(); ///< Called to switch off the DeviceVectorUI8 (rootnode).
	void start_DeviceVectorUI8();     ///< Called to start the DeviceVectorUI8 (rootnode).
	void stop_DeviceVectorUI8();      ///< Called to stop the DeviceVectorUI8 (rootnode).
	void recover_DeviceVectorUI8();   ///< Called to recover the DeviceVectorUI8 (rootnode) from a failure.

	bool allow__DeviceVectorUI8_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

	///////////////////////////////////////////////////////////////////////////////////////////////////////
	//  DATA ACQUISITION
	///////////////////////////////////////////////////////////////////////////////////////////////////////

	/**
	 * @brief DataAcquisition node
	 */
	nds::DataAcquisition<std::vector<std::uint8_t> > m_DataAcquisition;

	/**
	 * Methods to control DataAcquisition state machine
	 */
	void switchOn_DataAcquisition();  ///< Called to switch on the DataAcquisition node.
	void switchOff_DataAcquisition(); ///< Called to switch off the DataAcquisition node.
	void start_DataAcquisition();     ///< Called to start the DataAcquisition node.
	void stop_DataAcquisition();      ///< Called to stop the DataAcquisition node.
	void recover_DataAcquisition();   ///< Called to recover the DataAcquisition node from a failure.

	bool allow_DataAcquisition_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

	/**
	 * DataAcquisition setters
	 */
	void PV_DataAcquisition_Gain_Writer(const timespec& /*timestamp*/, const double& /*value*/);
	void PV_DataAcquisition_Offset_Writer(const timespec& /*timestamp*/, const double& /*value*/);
	void PV_DataAcquisition_Bandwidth_Writer(const timespec& /*timestamp*/, const double& /*value*/);
	void PV_DataAcquisition_Resolution_Writer(const timespec& /*timestamp*/, const double& /*value*/);
	void PV_DataAcquisition_Impedance_Writer(const timespec& /*timestamp*/, const double& /*value*/);
	void PV_DataAcquisition_Coupling_Writer(const timespec& /*timestamp*/, const std::int32_t& /*value*/);
	void PV_DataAcquisition_SignalRef_Writer(const timespec& /*timestamp*/, const std::int32_t& /*value*/);
	void PV_DataAcquisition_Ground_Writer(const timespec& /*timestamp*/, const std::int32_t& /*value*/);

	/**
	 * @brief Function that continuously acquires data generated by m_DataGeneration.
	 *        It is launched by start_DataAcquisition() in a separate thread.
	 */
	void DataAcquisition_thread_body();

	/**
	 * @brief A thread that runs DataAcquisition_thread_body().
	 */
	std::thread m_DataAcquisition_Thread;

	/**
	 * @brief A boolean flag that stop the DataAcquisition loop in DataAcquisition_thread_body()
	 *        when true.
	 */
	volatile bool m_bStop_DataAcquisition;


	///////////////////////////////////////////////////////////////////////////////////////////////////////
	//  DATA GENERATION
	///////////////////////////////////////////////////////////////////////////////////////////////////////

	/**
	 * @brief DataGeneration node
	 */
	nds::DataGeneration<std::vector<std::uint8_t>> m_DataGeneration;

	/**
	 * Methods to control DataGeneration state machine
	 */
	void switchOn_DataGeneration();  ///< Called to switch on the DataGeneration node.
	void switchOff_DataGeneration(); ///< Called to switch off the DataGeneration node.
	void start_DataGeneration();     ///< Called to start the DataGeneration node.
	void stop_DataGeneration();      ///< Called to stop the DataGeneration node.
	void recover_DataGeneration();   ///< Called to recover the DataGeneration node from a failure.

	bool allow_DataGeneration_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

	/**
	 * DataGeneration setters
	 */
	void PV_DataGeneration_Frequency_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_RefFrequency_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_Amp_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_Phase_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_UpdateRate_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_DutyCycle_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_Gain_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_Offset_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_Bandwidth_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_Resolution_Writer(const timespec& timestamp, const double& value);
	void PV_DataGeneration_Impedance_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_DataGeneration_Coupling_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_DataGeneration_SignalRef_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_DataGeneration_SignalType_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_DataGeneration_Ground_Writer(const timespec& timestamp, const std::int32_t& value);

	 /**
	  * @brief Function that continuously generates a sinusoidal wave to m_DataGeneration.
	  *        It is launched by start_DataGeneration() in a separate thread.
	  */
	 void DataGeneration_thread_body();

	 /**
	  * @brief A thread that runs DataGeneration_thread_body().
	  */
	 std::thread m_DataGeneration_Thread;

	 /**
	  * @brief A boolean flag that stop the DataGeneration loop in DataGeneration_thread_body()
	  *        when true.
	  */
	 volatile bool m_bStop_DataGeneration;

};

#endif // DEVICEVECTORUI8_H_
