/*
 * testDevice.h
 *
 *  Created on: Sep 7, 2017
 *      Author: ebernal
 */

#ifndef TESTDEVICE_H_
#define TESTDEVICE_H_

#include <memory>

#include <functional>
#include <math.h>
#include <unistd.h>
#include <iostream>
#include <thread>

#include <nds3/nds.h>

/**
 * @brief Class that declares and implement a fictional device for testing purposes of nds-core V3.
 *
 *
 * The class does not need to be derived from any special class, but its constructor must
 *  accept few mandatory parameters and should register the root node via Node::initialize().
 */
class sampleDevice
{
public:
	/**
	 * @brief Constructor.
	 *
	 * @param factory    the control system factory that requested the creation of the device
	 * @param device     the name given to the device
	 * @param parameters optional parameters passed to the device
	 */
	sampleDevice(nds::Factory& factory, const std::string& device, const nds::namedParameters_t& parameters);

private:

	/*
	 * @brief name of the device
	 */
	std::string m_name;

	///////////////////////////////////////////////////////////////////////////////////////////////////
	/// Variables to store simulated data
	///////////////////////////////////////////////////////////////////////////////////////////////////

	std::int32_t PVVariable_value_I32, PVDelegate_value_I32;
	double  PVVariable_value_DBL, PVDelegate_value_DBL;
	std::vector<std::int8_t> PVVariable_vector_I8, PVDelegate_vector_I8;
	std::vector<std::uint8_t> PVVariable_vector_UI8, PVDelegate_vector_UI8;
	std::vector<std::int32_t> PVVariable_vector_I32, PVDelegate_vector_I32;
	std::vector<double> PVVariable_vector_DBL, PVDelegate_vector_DBL;
	std::string PVVariable_value_string, PVDelegate_value_string;

	timespec timestamp_device, readtimeStamp;

	///////////////////////////////////////////////////////////////////////////////////////////////////////
	//  TEST DEVICE STATE MACHINE
	///////////////////////////////////////////////////////////////////////////////////////////////////////

	/**
	 * @brief sampleDevice state machine
	 */
    nds::StateMachine m_sampleDevice_stateMachine;

	/**
	 * Methods to control sampleDevice state machine
	 */
	void switchOn_sampleDevice();  ///< Called to switch on the sampleDevice (rootnode).
	void switchOff_sampleDevice(); ///< Called to switch off the sampleDevice (rootnode).
	void start_sampleDevice();     ///< Called to start the sampleDevice (rootnode).
	void stop_sampleDevice();      ///< Called to stop the sampleDevice (rootnode).
	void recover_sampleDevice();   ///< Called to recover the sampleDevice (rootnode) from a failure.

	bool allow_sampleDevice_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

	///////////////////////////////////////////////////////////////////////////////////////////////////////
	//  DATA ACQUISITION
    ///////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
	 * @brief DataAcquisition node
	 */
	nds::DataAcquisition<std::vector<double> > m_DataAcquisition;

	/**
	 * Methods to control DataAcquisition state machine
	 */
	void switchOn_DataAcquisition();  ///< Called to switch on the DataAcquisition node.
	void switchOff_DataAcquisition(); ///< Called to switch off the DataAcquisition node.
	void start_DataAcquisition();     ///< Called to start the DataAcquisition node.
	void stop_DataAcquisition();      ///< Called to stop the DataAcquisition node.
	void recover_DataAcquisition();   ///< Called to recover the DataAcquisition node from a failure.

	bool allow_DataAcquisition_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

	/**
	 * DataAcquisition setters
	 */
	void PV_DataAcquisition_Gain_Writer(const timespec& timestamp, const double& value);
	void PV_DataAcquisition_Offset_Writer(const timespec& timestamp, const double& value);
	void PV_DataAcquisition_Bandwidth_Writer(const timespec& timestamp, const double& value);
	void PV_DataAcquisition_Resolution_Writer(const timespec& timestamp, const double& value);
	void PV_DataAcquisition_Impedance_Writer(const timespec& timestamp, const double& value);
	void PV_DataAcquisition_Coupling_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_DataAcquisition_SignalRefType_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_DataAcquisition_Ground_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_DataAcquisition_DMAEnable_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_DataAcquisition_SamplingRate_Writer(const timespec& timestamp, const double& value);

    /**
     * @brief Function that continuously acquires data generated by m_WaveformGeneration.
     *        It is launched by start_DataAcquisition() in a separate thread.
     */
    void DataAcquisition_thread_body();

    /**
     * @brief A thread that runs DataAcquisition_thread_body().
     */
    std::thread m_DataAcquisition_Thread;

    /**
     * @brief A boolean flag that stop the DataAcquisition loop in DataAcquisition_thread_body()
     *        when true.
     */
    volatile bool m_bStop_DataAcquisition;

	///////////////////////////////////////////////////////////////////////////////////////////////////////
	//  WFG GENERATION
    ///////////////////////////////////////////////////////////////////////////////////////////////////////

    /**
	 * @brief WaveformGeneration node
	 */
	nds::WaveformGeneration<std::vector<double> > m_WaveformGeneration;

	/**
	 * Methods to control WaveformGeneration state machine
	 */
	void switchOn_WaveformGeneration();  ///< Called to switch on the WaveformGeneration node.
	void switchOff_WaveformGeneration(); ///< Called to switch off the WaveformGeneration node.
	void start_WaveformGeneration();     ///< Called to start the WaveformGeneration node.
	void stop_WaveformGeneration();      ///< Called to stop the WaveformGeneration node.
	void recover_WaveformGeneration();   ///< Called to recover the WaveformGeneration node from a failure.

	bool allow_WaveformGeneration_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

	/**
	 * WaveformGeneration setters
	 */
	void PV_WaveformGeneration_Frequency_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_RefFrequency_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_Amp_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_Phase_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_UpdateRate_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_DutyCycle_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_Gain_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_Offset_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_Bandwidth_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_Resolution_Writer(const timespec& timestamp, const double& value);
	void PV_WaveformGeneration_Impedance_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_WaveformGeneration_Coupling_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_WaveformGeneration_SignalRef_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_WaveformGeneration_SignalType_Writer(const timespec& timestamp, const std::int32_t& value);
	void PV_WaveformGeneration_Ground_Writer(const timespec& timestamp, const std::int32_t& value);

    /**
     * @brief Function that continuously generates a sinusoidal wave to m_WaveformGeneration.
     *        It is launched by start_WaveformGeneration() in a separate thread.
     */
    void WaveformGeneration_thread_body();

    /**
     * @brief A thread that runs WaveformGeneration_thread_body().
     */
    std::thread m_WaveformGeneration_Thread;

    /**
     * @brief A boolean flag that stop the WaveformGeneration loop in WaveformGeneration_thread_body()
     *        when true.
     */
    volatile bool m_bStop_WaveformGeneration;

    ///////////////////////////////////////////////////////////////////////////////////////////////////////
    	 //  DATA PROCESSING
    	 ///////////////////////////////////////////////////////////////////////////////////////////////////////

    	 /**
    	  * @brief DataProcessing node
    	  */
    	 nds::DataProcessing<std::vector<std::int32_t> > m_DataProcessing;

    	 /**
    	  * Methods to control DataProcessing state machine
    	  */
    	 void switchOn_DataProcessing();  ///< Called to switch on the DataProcessing node.
    	 void switchOff_DataProcessing(); ///< Called to switch off the DataProcessing node.
    	 void start_DataProcessing();     ///< Called to start the DataProcessing node.
    	 void stop_DataProcessing();      ///< Called to stop the DataProcessing node.
    	 void recover_DataProcessing();   ///< Called to recover the DataProcessing node from a failure.

    	 bool allow_DataProcessing_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

    	 /**
    	  * DataProcessing setters
    	  */
    	 void PV_DataProcessing_EnableFilter_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_FilterType_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_FilterParams_Writer(const timespec& /*timestamp*/, const std::vector<std::int32_t>& params);
    	 void PV_DataProcessing_EnableFFT_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_EnableSwFFT_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_FFTwindowType_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_FFTOverlap_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_FFTFrameSize_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_FFTSmooth_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_EnableDecimation_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_DecimationType_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_DecimationOffset_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_DataProcessing_RAW2Eng_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);

    	 /**
    	  * DataProcessing getters
    	  */
    	 void PV_DataProcessing_EnableFilter_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_FilterType_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_FilterParams_Reader(timespec* /*timestamp*/, std::vector<std::int32_t>* /*value*/);
    	 void PV_DataProcessing_EnableFFT_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_EnableSwFFT_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_FFTwindowType_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_FFTOverlap_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_FFTFrameSize_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_FFTSmooth_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_EnableDecimation_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_DecimationType_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_DecimationOffset_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	 void PV_DataProcessing_RAW2Eng_Reader(timespec* /*timestamp*/, int32_t* /*value*/);

    	 /**
    	  * @brief Function that continuously proccess data.
    	  *        It is launched by start_DataProcessing() in a separate thread.
    	  */
    	 void DataProcessing_thread_body();

    	 /**
    	  * @brief A thread that runs DataProcessing_thread_body().
    	  */
    	 std::thread m_DataProcessing_Thread;

    	 /**
    	  * @brief A boolean flag that stop the DataProcessing loop in DataProcessing_thread_body()
    	  *        when true.
    	  */
    	 volatile bool m_bStop_DataProcessing;

    	 ///////////////////////////////////////////////////////////////////////////////////////////////////////
    	 //  DIGITAL I/O
    	 ///////////////////////////////////////////////////////////////////////////////////////////////////////

    	 /**
    	  * @brief DigitalIO node
    	  */
    	 nds::DigitalIO<std::vector<std::int32_t> > m_DigitalIO;

    	 /**
    	  * Methods to control DigitalIO state machine
    	  */
    	 void switchOn_DigitalIO();  ///< Called to switch on the DigitalIO node.
    	 void switchOff_DigitalIO(); ///< Called to switch off the DigitalIO node.
    	 void start_DigitalIO();     ///< Called to start the DigitalIO node.
    	 void stop_DigitalIO();      ///< Called to stop the DigitalIO node.
    	 void recover_DigitalIO();   ///< Called to recover the DigitalIO node from a failure.

    	 bool allow_DigitalIO_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

    	 /**
    	  * DigitalIO setters
    	  */
    	 void PV_DigitalIO_dataOutMask_Writer(const timespec& timestamp, const std::vector<bool>& value);
    	 void PV_DigitalIO_voltLevelHigh_Writer(const timespec& timestamp, const double& value);
    	 void PV_DigitalIO_voltLevelLow_Writer(const timespec& timestamp, const double& value);
    	 void PV_DigitalIO_ChannelDir_Writer(const timespec& timestamp, const std::vector<bool>& value);

    	 /**
    	  * @brief Function that continuously acquires digital IO data.
    	  *        It is launched by start_DigitalIO() in a separate thread.
    	  */
    	 void DigitalIO_thread_body();

    	 /**
    	  * @brief A thread that runs DataProcessing_thread_body().
    	  */
    	 std::thread m_DigitalIO_Thread;

    	 /**
    	  * @brief A boolean flag that stop the DigitalIO loop in DigitalIO_thread_body()
    	  *        when true.
    	  */
    	 volatile bool m_bStop_DigitalIO;




    	 ///////////////////////////////////////////////////////////////////////////////////////////////////////
    	 //  STREAMING CONFIGURATION
    	 ///////////////////////////////////////////////////////////////////////////////////////////////////////

    	 /**
    	  * @brief Streaming node
    	  */
    	 nds::Streaming<std::vector<std::int32_t> > m_Streaming;

    	 /**
    	  * Methods to control Streaming state machine
    	  */
    	 void switchOn_Streaming();  ///< Called to switch on the Streaming node.
    	 void switchOff_Streaming(); ///< Called to switch off the Streaming node.
    	 void start_Streaming();     ///< Called to start the Streaming node.
    	 void stop_Streaming();      ///< Called to stop the Streaming node.
    	 void recover_Streaming();   ///< Called to recover the Streaming node from a failure.

    	 bool allow_Streaming_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

    	 /**
    	  * Streaming setters
    	  */
    	 void PV_Streaming_BufferSize_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_Streaming_Type_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_Streaming_DataFormat_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);

    	 /**
    	  * @brief Function that continuously streams data generated.
    	  *        It is launched by start_Streaming() in a separate thread.
    	  */
    	 void Streaming_thread_body();

    	 /**
    	  * @brief A thread that runs Streaming_thread_body().
    	  */
    	 std::thread m_Streaming_Thread;

    	 /**
    	  * @brief A boolean flag that stop the Streaming loop in Streaming_thread_body()
    	  *        when true.
    	  */
    	 volatile bool m_bStop_Streaming;

    	 ///////////////////////////////////////////////////////////////////////////////////////////////////////
    	 //  IMAGE ACQUISITION
    	 ///////////////////////////////////////////////////////////////////////////////////////////////////////

    	 /**
    	  * imageAcquisition node
    	  */
    	 nds::imageAcquisition<std::vector<double> > m_imageAcquisition;

    	 /**
    	  * Methods to control imageAcquisition state machine
    	  */
    	 void switchOn_imageAcquisition();  ///< Called to switch on the imageAcquisition node.
    	 void switchOff_imageAcquisition(); ///< Called to switch off the imageAcquisition node.
    	 void start_imageAcquisition();     ///< Called to start the imageAcquisition node.
    	 void stop_imageAcquisition();      ///< Called to stop the imageAcquisition node.
    	 void recover_imageAcquisition();   ///< Called to recover the imageAcquisition node from a failure.

    	 bool allow_imageAcquisition_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

    	 /**
    	  * imageAcquisition setters
    	  */
    	 void PV_imageAcquisition_BinX_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_BinY_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_MinX_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_MinY_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_SizeX_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_SizeY_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_ReverseX_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_ReverseY_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_Resolution_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_SamplesPerPixel_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_AcquireTime_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_AcquirePeriod_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_Gain_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_FrameType_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_LostFrames_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_ImageMode_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_TriggerMode_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_NumExposures_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_Exposure_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_minExposure_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_maxExposure_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_ExposureStep_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_BlackLevel_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_NumImages_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_Acquire_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_ReadStatus_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_ShutterMode_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_ShutterControlMode_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_DelayStep_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	 void PV_imageAcquisition_ShutterOpenDelay_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_ShutterMinOpenDelay_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_ShutterMaxOpenDelay_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_ShutterCloseDelay_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_ShutterMinCloseDelay_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_ShutterMaxCloseDelay_Writer(const timespec& /*timestamp*/, const double& /*value*/);
    	 void PV_imageAcquisition_HotPixels_Writer(const timespec& /*timestamp*/, const std::vector<std::int32_t>& /*value*/);
    	 void PV_imageAcquisition_HotPixelsCorr_Writer(const timespec& /*timestamp*/, const std::vector<std::int32_t>& /*value*/);
    	 void PV_imageAcquisition_Temperature_Writer(const timespec& /*timestamp*/, const double& /*value*/);

    	 /**
    	  * imageAcquisition getters
    	  */
    	  void PV_imageAcquisition_MaxSizeX_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_MaxSizeY_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_BinX_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_BinY_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_MinX_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_MinY_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_SizeX_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_SizeY_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_ReverseX_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_ReverseY_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_Resolution_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_SamplesPerPixel_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_AcquireTime_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_AcquirePeriod_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_TimeRemaining_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_Gain_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_FrameType_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_LostFrames_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_ImageMode_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_TriggerMode_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_NumExposures_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_NumExposuresCounter_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_Exposure_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_minExposure_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_maxExposure_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_ExposureStep_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_BlackLevel_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_NumImages_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_NumImagesCounter_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_Acquire_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_DetectorState_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_StatusMessage_Reader(timespec* /*timestamp*/, std::string* /*value*/);
    	  void PV_imageAcquisition_StringToServer_Reader(timespec* /*timestamp*/, std::string* /*value*/);
    	  void PV_imageAcquisition_StringFromServer_Reader(timespec* /*timestamp*/, std::string* /*value*/);
    	  void PV_imageAcquisition_ShutterMode_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_ShutterControlMode_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_ShutterStatus_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_DelayStep_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_imageAcquisition_ShutterOpenDelay_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_ShutterMinOpenDelay_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_ShutterMaxOpenDelay_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_ShutterCloseDelay_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_ShutterMinCloseDelay_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_ShutterMaxCloseDelay_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_HotPixels_Reader(timespec* /*timestamp*/, std::vector<std::int32_t>* /*value*/);
    	  void PV_imageAcquisition_HotPixelsCorr_Reader(timespec* /*timestamp*/, std::vector<std::int32_t>* /*value*/);
    	  void PV_imageAcquisition_Temperature_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_imageAcquisition_ActualTemperature_Reader(timespec* /*timestamp*/, double* /*value*/);

    	  /**
    	   * @brief Function that continuously acquires image data.
    	   *        It is launched by start_imageAcquisition() in a separate thread.
    	   */
    	  void imageAcquisition_thread_body();

    	  /**
    	   * @brief A thread that runs imageAcquisition_thread_body().
    	   */
    	  std::thread m_imageAcquisition_Thread;

    	  /**
    	   * @brief A boolean flag that stop the imageAcquisition loop in imageAcquisition_thread_body()
    	   *        when true.
    	   */
    	  volatile bool m_bStop_imageAcquisition;

    	  ///////////////////////////////////////////////////////////////////////////////////////////////////////
    	  //  HEALTH MONITORING SUPPORT
    	  ///////////////////////////////////////////////////////////////////////////////////////////////////////

    	  /**
    	   * @brief HQMonitor node
    	   */
    	  nds::HQMonitor m_HQMonitor;

    	  /**
    	   * Methods to control HQMonitor state machine
    	   */
    	  void switchOn_HQMonitor();  ///< Called to switch on the HQMonitor node.
    	  void switchOff_HQMonitor(); ///< Called to switch off the HQMonitor node.
    	  void start_HQMonitor();     ///< Called to start the HQMonitor node.
    	  void stop_HQMonitor();      ///< Called to stop the HQMonitor node.
    	  void recover_HQMonitor();   ///< Called to recover the HQMonitor node from a failure.

    	  bool allow_HQMonitor_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

    	  /**
    	   * HQMonitor setters
    	   */
    	  void PV_HQMonitor_EnableSEU_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	  void PV_HQMonitor_EnableMonitorDAQ_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	  void PV_HQMonitor_EnableShelfTest_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	  void PV_HQMonitor_SelfTestType_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	  void PV_HQMonitor_VerboseSelfTest_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	  void PV_HQMonitor_EnableSelfTestId_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	  void PV_HQMonitor_EnableSelfTestText_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	  void PV_HQMonitor_EnableCodeResultTest_Writer(const timespec& /*timestamp*/, const int32_t& /*value*/);
    	  void PV_HQMonitor_SignalQualityFlagLevel_Writer(const timespec& /*timestamp*/, const double& /*value*/);

    	  /**
    	   * HQMonitor getters
    	   */
    	  void PV_HQMonitor_DevicePower_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_HQMonitor_DeviceTemp_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_HQMonitor_DeviceVoltage_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_HQMonitor_DeviceCurrent_Reader(timespec* /*timestamp*/, double* /*value*/);
    	  void PV_HQMonitor_SignalQualityFlag_Reader(timespec* /*timestamp*/, int32_t* /*value*/);
    	  void PV_HQMonitor_SelfTestTxtResult_Reader(timespec* /*timestamp*/, std::string* /*value*/);

    	  /**
    	   * @brief Function that continuously acquires data related with health monitoring.
    	   *        It is launched by start_HQMonitor() in a separate thread.
    	   */
    	  void HQ_thread_body();

    	  /**
    	   * @brief A thread that runs HQMonitor_thread_body().
    	   */
    	  std::thread m_HQMonitor_Thread;

    	  /**
    	   * @brief A boolean flag that stop the HQMonitor loop in HQMonitor_thread_body()
    	   *        when true.
    	   */
    	  volatile bool m_bStop_HQMonitor;

    	  ///////////////////////////////////////////////////////////////////////////////////////////////////////
    	  //  Routing SUPPORT
    	  ///////////////////////////////////////////////////////////////////////////////////////////////////////

    	  /**
    	   * @brief Routing node
    	   */
    	  nds::Routing<std::string> m_Routing;

    	  /**
    	   * Methods to control Routing state machine
    	   */
    	  void switchOn_Routing();  ///< Called to switch on the Routing node.
    	  void switchOff_Routing(); ///< Called to switch off the Routing node.
    	  void start_Routing();     ///< Called to start the Routing node.
    	  void stop_Routing();      ///< Called to stop the Routing node.
    	  void recover_Routing();   ///< Called to recover the Routing node from a failure.
    	  bool allow_Routing_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

    	  /**
    	   * Routing setters
    	   */
    	  void PV_Routing_ClkSet_Writer(const timespec& timestamp, const std::int32_t& value);
    	  void PV_Routing_ClkDstRead_Writer(const timespec& timestamp, const std::int32_t& value);
    	  void PV_Routing_TermSet_Writer(const timespec& timestamp, const std::int32_t& value);
    	  void PV_Routing_TermDstRead_Writer(const timespec& timestamp, const std::int32_t& value);

    	  ///////////////////////////////////////////////////////////////////////////////////////////////////////
    	  //  FTE
    	  ///////////////////////////////////////////////////////////////////////////////////////////////////////

    	  /**
    	   * @brief DigitalIO node
    	   */
    	  nds::FTE<std::string> m_FTE;

    	  /**
    	   * Methods to control DigitalIO state machine
    	   */
    	  void switchOn_FTE();  ///< Called to switch on the FTE node.
    	  void switchOff_FTE(); ///< Called to switch off the FTE node.
    	  void start_FTE();     ///< Called to start the FTE node.
    	  void stop_FTE();      ///< Called to stop the FTE node.
    	  void recover_FTE();   ///< Called to recover the FTE node from a failure.

    	  bool allow_FTE_Change(const nds::state_t, const nds::state_t, const nds::state_t); ///< Called to verify if a state change is allowed

    	  /**
    	   * FTE setters
    	   */
      	  void PV_FTE_Set_Writer(const timespec& timestamp, const std::int32_t& value);
      	  void PV_FTE_Suppress_Writer(const timespec& timestamp, const std::int32_t& value);
      	  void PV_FTE_ChgPeriod_Writer(const timespec& timestamp, const std::int32_t& value);
      	  void PV_FTE_PendingValue_Writer(const timespec& timestamp, const std::int32_t& value);


	  ///////////////////////////////////////////////////////////////////////////////////////////////////////
	  //  EXTRA PVs for testing purposes
	  ///////////////////////////////////////////////////////////////////////////////////////////////////////


	  /**
	   * PVVariables In and Out for testing purposes
	   *      - std::int32_t
	   *      - double
	   *      - std::vector<std::int8_t>
	   *      - std::vector<std::uint8_t>
	   *      - std::vector<std::int32_t>
	   *      - std::vector<double>
	   *      - std::string
	   */
	   nds::PVVariableIn<std::int32_t> m_int32_VariableIn;
	   nds::PVVariableOut<std::int32_t> m_int32_VariableOut;

	   nds::PVVariableIn<double> m_double_VariableIn;
	   nds::PVVariableOut<double> m_double_VariableOut;

	   nds::PVVariableIn<std::vector<std::int8_t>> m_vectorI8_VariableIn;
	   nds::PVVariableOut<std::vector<std::int8_t>> m_vectorI8_VariableOut;

	   nds::PVVariableIn<std::vector<std::uint8_t>> m_vectorUI8_VariableIn;
	   nds::PVVariableOut<std::vector<std::uint8_t>> m_vectorUI8_VariableOut;

	   nds::PVVariableIn<std::vector<std::int32_t>> m_vectorI32_VariableIn;
	   nds::PVVariableOut<std::vector<std::int32_t>> m_vectorI32_VariableOut;

	   nds::PVVariableIn<std::vector<double>> m_vectorDBL_VariableIn;
	   nds::PVVariableOut<std::vector<double>> m_vectorDBL_VariableOut;

	   nds::PVVariableIn<std::string> m_string_VariableIn;
	   nds::PVVariableOut<std::string> m_string_VariableOut;

	   /**
	    * PVDelegates In and Out for testing purposes
	    *      - std::int32_t
	    *      - double
	    *      - std::vector<std::int8_t>
	    *      - std::vector<std::uint8_t>
	    *      - std::vector<std::int32_t>
	    *      - std::vector<double>
	    *      - std::string
	    */
	   nds::PVDelegateIn<std::int32_t> m_int32_DelegateIn;
	   nds::PVDelegateOut<std::int32_t> m_int32_DelegateOut;
	   nds::PVDelegateOut<std::int32_t> m_int32_DelegateOut_init;

	   nds::PVDelegateIn<double> m_double_DelegateIn;
	   nds::PVDelegateOut<double> m_double_DelegateOut;
	   nds::PVDelegateOut<double> m_double_DelegateOut_init;

	   nds::PVDelegateIn<std::vector<std::int8_t>> m_vectorI8_DelegateIn;
	   nds::PVDelegateOut<std::vector<std::int8_t>> m_vectorI8_DelegateOut;
	   nds::PVDelegateOut<std::vector<std::int8_t>> m_vectorI8_DelegateOut_init;

	   nds::PVDelegateIn<std::vector<std::uint8_t>> m_vectorUI8_DelegateIn;
	   nds::PVDelegateOut<std::vector<std::uint8_t>> m_vectorUI8_DelegateOut;
	   nds::PVDelegateOut<std::vector<std::uint8_t>> m_vectorUI8_DelegateOut_init;

	   nds::PVDelegateIn<std::vector<std::int32_t>> m_vectorI32_DelegateIn;
	   nds::PVDelegateOut<std::vector<std::int32_t>> m_vectorI32_DelegateOut;
	   nds::PVDelegateOut<std::vector<std::int32_t>> m_vectorI32_DelegateOut_init;

	   nds::PVDelegateIn<std::vector<double>> m_vectorDBL_DelegateIn;
	   nds::PVDelegateOut<std::vector<double>> m_vectorDBL_DelegateOut;
	   nds::PVDelegateOut<std::vector<double>> m_vectorDBL_DelegateOut_init;

	   nds::PVDelegateIn<std::string> m_string_DelegateIn;
	   nds::PVDelegateOut<std::string> m_string_DelegateOut;
	   nds::PVDelegateOut<std::string> m_string_DelegateOut_init;

	   ///////////////////////////////////////////////////////////////////////////////////////////////////
	   /// SETTERS/GETTERS FOR PVDELEGATE IN/OUT PVs
	   ///////////////////////////////////////////////////////////////////////////////////////////////////

	   void read_I32_DelegateIn(timespec* timestamp, std::int32_t* value);
	   void read_DBL_DelegateIn(timespec* timestamp, double* value);
	   void read_vectorI8_DelegateIn(timespec* timestamp, std::vector<std::int8_t>* value);
	   void read_vectorUI8_DelegateIn(timespec* timestamp, std::vector<std::uint8_t>* value);
	   void read_vectorI32_DelegateIn(timespec* timestamp, std::vector<std::int32_t>* value);
	   void read_vectorDBL_DelegateIn(timespec* timestamp, std::vector<double>* value);
	   void read_string_DelegateIn(timespec* timestamp, std::string* value);

	   void write_I32_DelegateOut(const timespec& timestamp, const std::int32_t& value);
	   void write_DBL_DelegateOut(const timespec& timestamp,const double& value);
	   void write_vectorI8_DelegateOut(const timespec& timestamp,const std::vector<std::int8_t>& value);
	   void write_vectorUI8_DelegateOut(const timespec& timestamp,const std::vector<std::uint8_t>& value);
	   void write_vectorI32_DelegateOut(const timespec& timestamp,const std::vector<std::int32_t>& value);
	   void write_vectorDBL_DelegateOut(const timespec& timestamp,const std::vector<double>& value);
	   void write_string_DelegateOut(const timespec& timestamp,const std::string& value);

	   void init_I32_DelegateOut(timespec* timestamp, std::int32_t* value);
	   void init_DBL_DelegateOut(timespec* timestamp, double* value);
	   void init_vectorI8_DelegateOut(timespec* timestamp, std::vector<std::int8_t>* value);
	   void init_vectorUI8_DelegateOut(timespec* timestamp, std::vector<std::uint8_t>* value);
	   void init_vectorI32_DelegateOut(timespec* timestamp, std::vector<std::int32_t>* value);
	   void init_vectorDBL_DelegateOut(timespec* timestamp, std::vector<double>* value);
	   void init_string_DelegateOut(timespec* timestamp, std::string* value);

	   /*
	    * PVs to test subscription, replication and decimation.
	    */

	   nds::PVVariableIn<std::string> m_testVariableIn;
	   nds::PVVariableOut<std::string> m_testVariableOut;

	   nds::PVDelegateIn<std::string> m_delegateIn;
	   nds::PVDelegateOut<std::string> m_delegateOut;
	   nds::PVDelegateOut<std::string>	m_writeTestVariableIn;
	   nds::PVDelegateOut<std::string>	m_pushTestVariableIn;
	   nds::PVDelegateIn<std::string>	m_readTestVariableOut;

	   void readDelegate(timespec* pTimestamp, std::string* pValue);
	   void writeDelegate(const timespec& timestamp, const std::string& value);

	   void writeTestVariableIn(const timespec& timestamp, const std::string& value);
	   void pushTestVariableIn(const timespec& timestamp, const std::string& value);
	   void readTestVariableOut(timespec* pTimestamp, std::string* pValue);

	   std::string m_writtenByDelegate;

	   nds::PVVariableOut<std::int32_t> m_setCurrentTime;
	   timespec getCurrentTime();
};

#endif /* TESTDEVICE_H_ */
