#include <nds3/nds.h>



class channel {

 public:

  /**
   *
   */
  channel(const std::string& name, nds::Node& parent);
  /**
   *
   */
  ~channel();

  // WARNING: por que' lo que viene por debajo es public y no private

  nds::PVVariableOut<double> m_amplitude;

  nds::PVVariableOut<double> m_frequency;


  //////////////////////////////////////////////////////////////////////////////
  /// Data Acquisition Node ////////////////////////////////////////////////////
  //////////////////////////////////////////////////////////////////////////////

  /**
   * Methods to control Data Acquisition state machine
   */
  nds::DataAcquisition<std::vector<double>> m_acquisition;
  void switchon_acquisition();    ///< Called to switch on the DataAcquisition node.
  void switchoff_acquisition();   ///< Called to switch off the DataAcquisition node.
  void start_acquisition();       ///< Called to start the DataAcquisition node.
  void stop_acquisition();        ///< Called to stop the DataAcquisition node.
  void recover_acquisition();     ///< Called to recover the DataAcquisition node from a failure.
  bool allowChange_acquisition(const nds::state_t,
             const nds::state_t,
             const nds::state_t); ///< Called to verify if a state change is allowed
  /**
   * Data acquisition setters
   */
  void pv_gain_writer(const timespec& timestamp, const double& value);
  void pv_offset_writer(const timespec& timestamp, const double& value);
  void pv_bandwidth_writer(const timespec& timestamp, const double& value);
  void pv_resolution_writer(const timespec& timestamp, const double& value);
  void pv_impedance_writer(const timespec& timestamp, const double& value);
  void pv_coupling_writer(const timespec& timestamp, const std::int32_t& value);
  void pv_signalRefType_writer(const timespec& timestamp, const std::int32_t& value);
  void pv_ground_writer(const timespec& timestamp, const std::int32_t& value);
  void pv_dmaEnable_writer(const timespec& timestamp, const std::int32_t& value);
  void pv_samplingRate_writer(const timespec& timestamp, const double& value);

  /**
   * @brief Function that continuously acquires data generated by m_WaveformGeneration.
   *        It is launched by start_acquisition() in a separate thread.
   */
  void acquisition_thread_body();

  /**
   * @brief A thread that runs acquisition_thread_body().
   */
  std::thread m_acquisition_thread;

  /**
   * @brief A boolean flag that stops the DataAcquisition loop in acquisition_thread_body()
   *        when true.
   */
  volatile bool m_stop_acquisition;

  //////////////////////////
  // End Data Acquisition //
  //////////////////////////
 protected:

 private:

};
